POST http://localhost:3001/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "patrikkk@gmail.com",
    "password": "HEJSANNNnhejsann123###"
}

###
POST http://localhost:3001/auth/login HTTP/1.1
content-type: application/json

{
    "username": "patrikkk@gmail.com",
    "password": "HEJSANNNnhejsann123###"
}

###

POST http://localhost:3001/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "P@g.com",
    "password": "AAAaaa123###"
}

###

POST http://localhost:3001/auth/login HTTP/1.1
content-type: application/json

{
    "username": "P@g.com",
    "password": "AAAaaa123###"
}

###

GET http://localhost:3001/conversation/ HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwYTZhMGU0ZDZlMzVmMTc3YzU0ZGM3MiIsInVzZXJuYW1lIjoicGF0cmlra2tAZ21haWwuY29tIn0sImlhdCI6MTYyMjEzMDExNX0.QjJZL5uyrvbkcWn7w47r1VOE51TLevaGtPBi1eGivQM

